version: '3.8'
services:
  db:
    image: postgres:14
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: simple_bank
    networks:
      - myworldcamp
networks:
  myworldcamp:
